#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from python.common import (
    format_currency,
    format_percent,
    format_population,
    log_info,
    log_warn,
    resolve_output_path,
    safe_float,
    safe_int,
    try_fetch_json,
    wikipedia_best_effort,
    write_json,
)

DEFAULT_OUTPUT = "data/raw/regions.json"
DEFAULT_STATIONS = "data/raw/stations.json"
DEFAULT_ROUTES = "data/raw/routes.json"
CENSUS_URLS = [
    "https://api.census.gov/data/2022/acs/acs5?get=NAME,B01003_001E,B19013_001E,B17001_002E,B17001_001E,B08201_002E,B08201_001E&for=state:*",
    "https://api.census.gov/data/2021/acs/acs5?get=NAME,B01003_001E,B19013_001E,B17001_002E,B17001_001E,B08201_002E,B08201_001E&for=state:*",
]

FIPS_TO_CODE = {
    "01": "AL",
    "02": "AK",
    "04": "AZ",
    "05": "AR",
    "06": "CA",
    "08": "CO",
    "09": "CT",
    "10": "DE",
    "11": "DC",
    "12": "FL",
    "13": "GA",
    "15": "HI",
    "16": "ID",
    "17": "IL",
    "18": "IN",
    "19": "IA",
    "20": "KS",
    "21": "KY",
    "22": "LA",
    "23": "ME",
    "24": "MD",
    "25": "MA",
    "26": "MI",
    "27": "MN",
    "28": "MS",
    "29": "MO",
    "30": "MT",
    "31": "NE",
    "32": "NV",
    "33": "NH",
    "34": "NJ",
    "35": "NM",
    "36": "NY",
    "37": "NC",
    "38": "ND",
    "39": "OH",
    "40": "OK",
    "41": "OR",
    "42": "PA",
    "44": "RI",
    "45": "SC",
    "46": "SD",
    "47": "TN",
    "48": "TX",
    "49": "UT",
    "50": "VT",
    "51": "VA",
    "53": "WA",
    "54": "WV",
    "55": "WI",
    "56": "WY",
}

CODE_TO_NAME = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
}


def placeholder_region(code: str) -> dict[str, Any]:
    upper_code = code.strip().upper()
    name = CODE_TO_NAME.get(upper_code, upper_code)
    return {
        "name": name,
        "code": upper_code,
        "population": "0",
        "medianHouseholdIncome": "$0",
        "noVehicleAvailable": "0.0%",
        "povertyStatus": "0.0%",
        "publicTransportationToWork": ["Data unavailable"],
        "imageUrl": f"https://picsum.photos/seed/railreach-region-{upper_code.lower()}/1600/900",
        "wikipediaUrl": f"https://en.wikipedia.org/wiki/{name.replace(' ', '_')}",
        "tourismUrl": "",
        "twitterUrl": None,
        "railroadsOverview": "Placeholder overview generated by fallback mode.",
        "numberOfAmtrakStations": 0,
        "numberOfAmtrakRoutes": 0,
    }


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Scrape region data from Census ACS")
    parser.add_argument("--output", default=DEFAULT_OUTPUT, help="Output JSON path")
    parser.add_argument(
        "--stations-file",
        default=DEFAULT_STATIONS,
        help="Optional stations JSON for station counts",
    )
    parser.add_argument(
        "--routes-file",
        default=DEFAULT_ROUTES,
        help="Optional routes JSON for route counts",
    )
    parser.add_argument("--timeout", type=int, default=30, help="Request timeout seconds")
    parser.add_argument(
        "--no-wikipedia",
        action="store_true",
        help="Skip Wikipedia enrichment lookups",
    )
    return parser.parse_args()


def enrich_region_with_wikipedia(
    region: dict[str, Any],
    timeout: int,
    use_wikipedia: bool,
    wiki_cache: dict[str, dict[str, Any] | None],
) -> dict[str, Any]:
    name = str(region.get("name", "")).strip()
    code = str(region.get("code", "")).strip().upper()

    if use_wikipedia and name:
        cache_key = name.lower()
        summary = wiki_cache.get(cache_key)
        if cache_key not in wiki_cache:
            summary = wikipedia_best_effort(
                title_candidates=[name],
                search_query=f"{name} U.S. state",
                timeout=timeout,
            )
            wiki_cache[cache_key] = summary

        if summary:
            extract = str(summary.get("extract", "")).strip()
            summary_image = (
                (summary.get("originalimage") or {}).get("source")
                or (summary.get("thumbnail") or {}).get("source")
                or ""
            )
            page_url = (summary.get("content_urls") or {}).get("desktop", {}).get("page", "")

            if extract and (
                not region.get("railroadsOverview")
                or region.get("railroadsOverview") == "Placeholder overview generated by fallback mode."
                or region.get("railroadsOverview") == "Region-level demographics sourced from U.S. Census ACS."
            ):
                region["railroadsOverview"] = extract

            if summary_image and not region.get("imageUrl"):
                region["imageUrl"] = summary_image

            if page_url and not region.get("wikipediaUrl"):
                region["wikipediaUrl"] = page_url

    if not region.get("imageUrl"):
        region["imageUrl"] = f"https://picsum.photos/seed/railreach-region-{code.lower()}/1600/900"

    if not region.get("tourismUrl"):
        tourism_slug = name.lower().replace(" ", "-")
        region["tourismUrl"] = f"https://www.visittheusa.com/state/{tourism_slug}"

    return region


def enrich_counts(
    regions: list[dict[str, Any]],
    stations_path: Path,
    routes_path: Path,
) -> list[dict[str, Any]]:
    station_counts: dict[str, int] = {}
    route_counts: dict[str, int] = {}

    if stations_path.exists():
        try:
            station_data = json.loads(stations_path.read_text(encoding="utf-8"))
            if isinstance(station_data, list):
                for station in station_data:
                    if not isinstance(station, dict):
                        continue
                    code = str(station.get("regionId", "")).strip().upper()
                    if code:
                        station_counts[code] = station_counts.get(code, 0) + 1
        except json.JSONDecodeError as error:
            log_warn(f"Could not read stations file for enrichment: {error}")

    if routes_path.exists():
        try:
            route_data = json.loads(routes_path.read_text(encoding="utf-8"))
            if isinstance(route_data, list):
                for route in route_data:
                    if not isinstance(route, dict):
                        continue
                    regions_spanned = route.get("regionsSpanned", [])
                    if isinstance(regions_spanned, list):
                        region_codes = [str(c).strip().upper() for c in regions_spanned if c]
                    else:
                        region_codes = [
                            item.strip().upper() for item in str(regions_spanned).split(",") if item.strip()
                        ]
                    for code in set(region_codes):
                        route_counts[code] = route_counts.get(code, 0) + 1
        except json.JSONDecodeError as error:
            log_warn(f"Could not read routes file for enrichment: {error}")

    by_code: dict[str, dict[str, Any]] = {}
    for region in regions:
        code = str(region.get("code", "")).upper()
        if not code:
            continue
        by_code[code] = region

    coverage_codes = {
        code
        for code in (set(station_counts.keys()) | set(route_counts.keys()))
        if code in CODE_TO_NAME
    }
    for code in sorted(coverage_codes):
        if code not in by_code:
            by_code[code] = placeholder_region(code)

    for code, region in by_code.items():
        region["numberOfAmtrakStations"] = station_counts.get(code, 0)
        region["numberOfAmtrakRoutes"] = route_counts.get(code, 0)

    return sorted(by_code.values(), key=lambda item: str(item.get("name", "")))


def regions_from_census_payload(payload: Any) -> list[dict[str, Any]]:
    if not isinstance(payload, list) or len(payload) < 2:
        return []

    header = payload[0]
    rows = payload[1:]
    if not isinstance(header, list):
        return []

    col_index = {str(column): idx for idx, column in enumerate(header)}

    regions: list[dict[str, Any]] = []
    for row in rows:
        if not isinstance(row, list):
            continue

        def get(name: str, fallback: str = "") -> str:
            idx = col_index.get(name)
            if idx is None or idx >= len(row):
                return fallback
            return str(row[idx])

        fips = get("state")
        code = FIPS_TO_CODE.get(fips, "")
        if not code:
            continue

        name = get("NAME", code)
        population = safe_int(get("B01003_001E"))
        median_income = safe_int(get("B19013_001E"))
        poverty_numerator = safe_float(get("B17001_002E"))
        poverty_denominator = safe_float(get("B17001_001E"))
        no_vehicle_numerator = safe_float(get("B08201_002E"))
        no_vehicle_denominator = safe_float(get("B08201_001E"))

        region = {
            "name": name,
            "code": code,
            "population": format_population(population),
            "medianHouseholdIncome": format_currency(median_income),
            "noVehicleAvailable": format_percent(no_vehicle_numerator, no_vehicle_denominator),
            "povertyStatus": format_percent(poverty_numerator, poverty_denominator),
            "publicTransportationToWork": [
                "Transit providers vary by metro area",
                "See local MPO and state DOT resources",
            ],
            "imageUrl": "",
            "wikipediaUrl": f"https://en.wikipedia.org/wiki/{name.replace(' ', '_')}",
            "tourismUrl": "",
            "twitterUrl": None,
            "railroadsOverview": "Region-level demographics sourced from U.S. Census ACS.",
            "numberOfAmtrakStations": 0,
            "numberOfAmtrakRoutes": 0,
        }
        regions.append(region)

    return sorted(regions, key=lambda item: str(item.get("name", "")))


def fallback_regions() -> list[dict[str, Any]]:
    log_warn("Using fallback regions data (network source unavailable)")
    return [placeholder_region(code) for code in sorted(CODE_TO_NAME.keys())]


def main() -> int:
    args = parse_args()
    repo_root = Path(__file__).resolve().parents[2]
    output_path = resolve_output_path(repo_root, args.output)
    stations_path = resolve_output_path(repo_root, args.stations_file)
    routes_path = resolve_output_path(repo_root, args.routes_file)
    wiki_cache: dict[str, dict[str, Any] | None] = {}

    try:
        payload, source_url = try_fetch_json(CENSUS_URLS, timeout=args.timeout)
        regions = regions_from_census_payload(payload)
        log_info(f"Fetched {len(regions)} region records from {source_url}")
    except RuntimeError as error:
        log_warn(str(error))
        regions = fallback_regions()

    regions = enrich_counts(regions, stations_path=stations_path, routes_path=routes_path)
    regions = [
        enrich_region_with_wikipedia(
            region,
            timeout=args.timeout,
            use_wikipedia=not args.no_wikipedia,
            wiki_cache=wiki_cache,
        )
        for region in regions
    ]
    write_json(output_path, regions)
    log_info(f"Wrote {len(regions)} region records to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
