"""add region railroads_overview and amtrak counts

Revision ID: 3a951eafb9c3
Revises: f06e2d75169b
Create Date: 2026-03-10 19:15:24.209429

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3a951eafb9c3"
down_revision: Union[str, Sequence[str], None] = "f06e2d75169b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("regions", sa.Column("railroads_overview", sa.Text(), nullable=True))
    op.add_column(
        "regions", sa.Column("number_of_amtrak_stations", sa.Integer(), nullable=True)
    )
    op.add_column(
        "regions", sa.Column("number_of_amtrak_routes", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("regions", "number_of_amtrak_routes")
    op.drop_column("regions", "number_of_amtrak_stations")
    op.drop_column("regions", "railroads_overview")
    # ### end Alembic commands ###
