"""initial schema with junction tables

Revision ID: f06e2d75169b
Revises:
Create Date: 2026-03-10 18:58:30.467867

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "f06e2d75169b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "destinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "points_of_interest",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("population", sa.Integer(), nullable=True),
        sa.Column("median_household_income", sa.Integer(), nullable=True),
        sa.Column("no_vehicle_available_percent", sa.Float(), nullable=True),
        sa.Column("poverty_rate_percent", sa.Float(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("wikipedia_url", sa.Text(), nullable=True),
        sa.Column("tourism_url", sa.Text(), nullable=True),
        sa.Column("twitter_url", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("travel_time_in_hours", sa.Text(), nullable=True),
        sa.Column("regions_spanned", sa.Text(), nullable=True),
        sa.Column("stations_served", sa.Integer(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("amtrak_url", sa.Text(), nullable=True),
        sa.Column("wikipedia_url", sa.Text(), nullable=True),
        sa.Column("youtube_url", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "stops",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "transport_systems",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "region_transport_systems",
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("transport_system_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transport_system_id"],
            ["transport_systems.id"],
        ),
        sa.PrimaryKeyConstraint("region_id", "transport_system_id"),
    )
    op.create_table(
        "route_major_stops",
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("stop_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stop_id"],
            ["stops.id"],
        ),
        sa.PrimaryKeyConstraint("route_id", "stop_id"),
    )
    op.create_table(
        "route_menu_items",
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_item_id"],
            ["menu_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("route_id", "menu_item_id"),
    )
    op.create_table(
        "stations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("timezone", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("hours", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("routes_served_count", sa.Integer(), nullable=True),
        sa.Column("amtrak_url", sa.Text(), nullable=True),
        sa.Column("wikipedia_url", sa.Text(), nullable=True),
        sa.Column("facebook_url", sa.Text(), nullable=True),
        sa.Column("twitter_url", sa.Text(), nullable=True),
        sa.Column("poi_image_url", sa.Text(), nullable=True),
        sa.Column("poi_image_label", sa.Text(), nullable=True),
        sa.Column("history", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "station_connected_destinations",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("destination_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["destination_id"],
            ["destinations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("station_id", "destination_id"),
    )
    op.create_table(
        "station_nearby_stations",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("nearby_station_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["nearby_station_id"],
            ["stations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("station_id", "nearby_station_id"),
    )
    op.create_table(
        "station_points_of_interest",
        sa.Column("station_id", sa.Integer(), nullable=False),
        sa.Column("point_of_interest_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["point_of_interest_id"],
            ["points_of_interest.id"],
        ),
        sa.ForeignKeyConstraint(
            ["station_id"],
            ["stations.id"],
        ),
        sa.PrimaryKeyConstraint("station_id", "point_of_interest_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("station_points_of_interest")
    op.drop_table("station_nearby_stations")
    op.drop_table("station_connected_destinations")
    op.drop_table("stations")
    op.drop_table("route_menu_items")
    op.drop_table("route_major_stops")
    op.drop_table("region_transport_systems")
    op.drop_table("transport_systems")
    op.drop_table("stops")
    op.drop_table("routes")
    op.drop_table("regions")
    op.drop_table("points_of_interest")
    op.drop_table("menu_items")
    op.drop_table("destinations")
    # ### end Alembic commands ###
